# -*- coding: utf-8 -*-
"""automated-conversion-wikitext

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MhKNguxgvTYho-OSnk-11wk0CgYorgGz
"""

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

worksheet = gc.open('Wikidata Property Proposal  (Responses)').sheet1

# Menampilkan data pada gspread
data = worksheet.get_all_values()
print(data)

# Konversi gspread menjadi DataFrame
import pandas as pd
pd.DataFrame.from_records(data)

nama_kolom = ["nama_properti", "deskripsi_properti", "raw_butir_subjek", "tipe_data", "raw_domain", "pranala_sumber", "contoh_1", "contoh_2", 
              "contoh_3", "contoh_4", "rencana_penggunaan", "raw_kelengkapan", "format_pranala", "proyek_terkait", "motivasi", "sub_halaman"]

# Membuat list kolom yang berisikan nilai pada baris terakhir DataFrame
for kolom in nama_kolom:
  kolom = []
  kolom += data[-1][1:14] + data[-1][15:18]         # Index 14 tidak dibutuhkan
  kolom[2] = kolom[2][1:]; kolom[4] = kolom[4][1:]  # Menghapus char "Q"
  kolom[11] = 21873886 if "Always Incomplete (Q21873886)" else 21873974

# fungsi data_to_wiki_text() menerima input berupa multiple argument 
# multiple argument yang berisi nilai-nilai pada baris terakhir DataFrame 
# kemudian mengkonversikannya menjadi output berupa wiki text (tipe string)

def data_to_wiki_text(*kolom):
  for k in kolom:
    return f'''
==={{{{TranslateThis | anchor = en | en = {k[0]}}}}} ===
{{Property proposal
|status = P10770
|description = {{{{TranslateThis | en = {k[1]}}}}}
|subject item = {{{{Q|{k[2]}}}}}
|infobox parameter = 
|datatype = {k[3]}
|domain = {{{{Q|{k[4]}}}}}
|allowed values = 
|allowed units = 
|source = {k[5]}
|example 1 = {k[6]}
|example 2 = {k[7]}
|example 3 = {k[8]}
|example 4 = {k[9]}
|planned use = {k[10]}
|number of ids = 
|expected completeness = {{{{Q|{k[11]}}}}}
|formatter URL = {k[12]}
|external links = 
|see also = 
|robot and gadget jobs = 
|subpage    = {k[-1]}
|topic = authority control
|applicable stated in value = {{{{Q|{k[2]}}}}}
|single value constraint = 
|distinct values constraint = 
|Wikidata project = [[Wikidata:{k[-3]}]]

====Motivation====
 
{k[-2]}
 
===={{int:Talk}}====
'''

wiki_text = data_to_wiki_text(kolom)
print(wiki_text)